<?php
$viewModel = $block->getParentBlock()->getViewModel();
if($viewModel->showAnyDayDeliveryInfo()):
    $content = $viewModel->getAnyDayDeliveryContent();
    if ($content):
?>
        <div class="mainContainer block-content any-day-delivery-info width-80">
            <div class="block-title">
                <h2><?= $viewModel->getAnyDayDeliveryBlockTitle() ?></h2>
                <div class="heading-divider heading-divider--short"></div>
            </div>
            <div class="content">
                <p><?= $content ?></p>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>