<?php
$viewModel = $block->getParentBlock()->getViewModel();
if($viewModel->showBlock2()):
    $content = $viewModel->getBlock2Content();
    if ($content):
?>
        <div class="mainContainer block-content block2 width-80">
            <div class="block-title">
                <span><?= $viewModel->getBlock2Title() ?></span>
                <div class="heading-divider heading-divider--short"></div>
            </div>
            <div class="content">
                <p><?= $content ?></p>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>