<div class="shortcoe-tooltip" style="color: red;margin-bottom: 50px;">
    <strong>NOTE : </strong> all the content configurations textboxes, you can use below short codes for rendering different dynamic data.<br/>
    <strong>{city}</strong> = This will display the current city name, 
    <strong>{category}</strong> = This will display the current category name in the city category page, 
    <strong>{country}</strong> = This will display the city country name, 
    <strong>{region}</strong> = This will display the city region name, 
    <strong>{website}</strong> = This will display the website name    
</div>